---
# Source: test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: default
data:
  vault-agent.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "my-k8s-role"
        }
      }
    }

    cache {
      use_auto_auth_token = true
    }

    listener "tcp" {
      address = "127.0.0.1:8200"
      tls_disable = true
    }

    sink "file" {
      path = "/vault/secrets/token"
    }

  template.hcl: |
    template {
      destination = "/vault/secrets/.env"
      contents = <<EOT
      USERNAME="{{ with secret "secret/data/{{ .Values.vault.usernamePath }}" }}{{ .Data.data.{{ .Values.vault.usernameKey }} }}{{ end }}"
      PASSWORD="{{ with secret "secret/data/{{ .Values.vault.passwordPath }}" }}{{ .Data.data.{{ .Values.vault.passwordKey }} }}{{ end }}"
      EOT
    }
